"""update_schemas_for_kotani_and_nulls

Revision ID: f3f7a7a4ad4e
Revises: 0002_payment_jobs
Create Date: 2026-05-15 23:16:25.903407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f7a7a4ad4e'
down_revision = '0002_payment_jobs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
